# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headImg',
            field=models.ImageField(upload_to='./Upload/'),
        ),
    ]
